apiVersion: v1
kind: Service
metadata:
  name: hello-svc-nodeport
spec:
  selector:
    app: hello-app 
  type: NodePort # type NodePort
  ports:
    - port: 5005 # port of the service, for inside communication
      targetPort: 5005 # port of the container
      nodePort: 31000 # port of the worker node