apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: hello-app
spec: # All information about replicaSet
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template: # all pods information, APP-NAME is important
    metadata:
      labels:
        app: hello-app
    spec:  
      containers:
      - image: david86854/demoapp:v0.1.0
        name: hello-app-container
        ports:
          - containerPort: 5005